version: "3.6"
services:

  neo4j:
    image: neo4j:enterprise
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./storage/neo4j/data:/data
      - ./storage/neo4j/logs:/logs
      - ./storage/neo4j/conf:/conf
      - ./storage/neo4j/import:/var/lib/neo4j/import
      - ./storage/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/testpassword
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
